site_name: "[kro]bot"
site_description: Le club de robotique de l'ENS Paris-Saclay
copyright: "Copyright &copy; Krobot 2019"
repo_url: https://github.com/ens-krobot/KrobotDocumentation/
nav:
    - Club et Matériel:
      - Le club: index.md
      - Les imprimantes 3D: imprimantes-3d.md
    - Projets:
      - Le KBOT: kbot.md
      - La Coupe de France: coupe-de-france.md
extra:
  search:
    language: fr
  social:
    - type: github
      link: https://github.com/ens-krobot
theme:
  name: material
  language: fr
  palette:
    primary: 'light green'
    accent: 'light green'
  logo: img/logo.svg
  favicon: img/favicon.ico
  font: false
  feature:
    tabs: true
extra_css:
  - css/layout.css
