site_name: "[kro]bot"
site_description: Le club de robotique de l'ENS Paris-Saclay
copyright: "Copyright &copy; Krobot 2019"
repo_url: https://github.com/ens-krobot/KrobotDocumentation/
nav:
    - Club et Matériel:
      - Le club: index.md
      - Ressources: ressources.md
      - Les imprimantes 3D: imprimantes-3d.md
    - Projets:
      - Le KBOT: kbot.md
      - Coupe de France 2019: coupe-de-france-2019.md
      - Coupe de France 2015: coupe-de-france-2015.md
      - Coupe de France 2012: coupe-de-france-2012.md
      - Coupe de France 2011: coupe-de-france-2011.md
      - Coupe de France 2010: coupe-de-france-2010.md
      - Coupe de France 2008: coupe-de-france-2008.md
      - Carte multi capteurs USB (2007): carte-multi-capteurs.md
      - Coupe de France 2007: coupe-de-france-2007.md
      - Coupe de France 2002: coupe-de-france-2002.md
      - Coupe de France 2001: coupe-de-france-2001.md
      - Coupe de France 2000: coupe-de-france-2000.md
      - Coupe de France 1999: coupe-de-france-1999.md
      - Coupe de France 1998: coupe-de-france-1998.md
      - Coupe de France 1997: coupe-de-france-1997.md
      - Coupe de France 1996: coupe-de-france-1996.md
extra:
  search:
    language: fr
  social:
    - type: github
      link: https://github.com/ens-krobot
theme:
  name: material
  language: fr
  palette:
    primary: 'light green'
    accent: 'light green'
  logo: img/logo.svg
  favicon: img/favicon.ico
  font: false
  feature:
    tabs: true
extra_css:
  - css/layout.css
markdown_extensions:
  - attr_list
  - smarty
